### ISSUE TITLE
请问clash打开时报502的问题怎么解决

### ISSUE THREAD

**Issue by bigtailfish** [xpf0000/FlyEnv#232]
关掉clash的系统代理就ok，打开就报502，请问有什么好方法解决？
我尝试在yaml里写上
  - DOMAIN-SUFFIX,localhost,DIRECT
  - DOMAIN-SUFFIX,127.0.0.1,DIRECT
  - DOMAIN-SUFFIX,.test,DIRECT
都不成功
请教一下，如何解决这个问题，谢谢！

**Comment by xpf0000** [comment]
我用的的ClashX. 只要不开增强模式, 就不会有这个问题. 

下面是deepseek的答案. 你可以尝试下
 
# 解决 Clash 导致 hosts 文件失效的问题

当 Clash 开启时 hosts 文件定义的域名无法正常工作并报 502 错误，通常是因为 Clash 的 DNS 处理方式与系统 hosts 文件冲突。以下是几种解决方法：

## 方法一：在 Clash 配置中启用 hosts 文件

1. 编辑 Clash 配置文件 (通常为 `config.yaml`)
2. 在 DNS 部分添加或修改以下内容：

```yaml
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 114.114.114.114
    - 8.8.8.8
  fallback:
    - tls://1.1.1.1:853
  hosts:
    use-hosts: true  # 启用系统 hosts 文件
```

## 方法二：将 hosts 条目直接写入 Clash 配置

```yaml
dns:
  hosts:
    'example.com': '192.168.1.100'  # 把你的 hosts 映射写在这里
```

## 方法三：调整 Clash 的 DNS 模式

尝试将 DNS 模式改为 `fake-ip`：

```yaml
dns:
  enhanced-mode: fake-ip
```

## 方法四：检查代理规则

确保你的规则没有错误地将这些域名代理到错误的地址：

```yaml
rules:
  - DOMAIN,example.com,DIRECT  # 确保本地域名直连
```

## 其他注意事项

1. 修改配置后需要重启 Clash 服务
2. 检查系统 DNS 设置是否被 Clash 修改
3. 确保 hosts 文件格式正确（IP在前，域名在后，用空格分隔）
4. 在 Windows 上可能需要以管理员权限运行 Clash

如果问题仍然存在，可以尝试使用 `dig` 或 `nslookup` 命令检查域名解析是否按预期工作。
